[SERVICE]
    Flush         1
    Log_Level     info
    Parsers_File  parsers.conf
    Parsers_File  parsers_custom.conf

[INPUT]
    Name    forward
    Listen  0.0.0.0
    Port    24224

[FILTER]
    Name          parser
    Match         gophprofile.*
    Key_Name      log
    Parser        gophprofile_json
    Reserve_Data  On

[OUTPUT]
    Name                opensearch
    Match               gophprofile.*
    Host                opensearch
    Port                9200
    Index               gophprofile-logs
    Suppress_Type_Name  On
    Logstash_Format     On
    Logstash_Prefix     gophprofile-logs
    Retry_Limit         False
