// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AvatarStatus.
const (
	Failed     AvatarStatus = "failed"
	Processing AvatarStatus = "processing"
	Ready      AvatarStatus = "ready"
)

// Defines values for AvatarMetadataMimeType.
const (
	Imagejpeg AvatarMetadataMimeType = "image/jpeg"
	Imagepng  AvatarMetadataMimeType = "image/png"
	Imagewebp AvatarMetadataMimeType = "image/webp"
)

// Defines values for ComponentHealthStatus.
const (
	ComponentHealthStatusHealthy   ComponentHealthStatus = "healthy"
	ComponentHealthStatusUnhealthy ComponentHealthStatus = "unhealthy"
)

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusHealthy   HealthResponseStatus = "healthy"
	HealthResponseStatusUnhealthy HealthResponseStatus = "unhealthy"
)

// Defines values for ThumbnailSize.
const (
	ThumbnailSizeN100x100 ThumbnailSize = "100x100"
	ThumbnailSizeN300x300 ThumbnailSize = "300x300"
)

// Defines values for GetAvatarParamsSize.
const (
	GetAvatarParamsSizeN100x100 GetAvatarParamsSize = "100x100"
	GetAvatarParamsSizeN300x300 GetAvatarParamsSize = "300x300"
	GetAvatarParamsSizeOriginal GetAvatarParamsSize = "original"
)

// Avatar defines model for Avatar.
type Avatar struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`

	// Status Текущее состояние асинхронной обработки.
	Status AvatarStatus `json:"status"`
	Url    string       `json:"url"`
	UserId string       `json:"user_id"`
}

// AvatarStatus Текущее состояние асинхронной обработки.
type AvatarStatus string

// AvatarMetadata defines model for AvatarMetadata.
type AvatarMetadata struct {
	CreatedAt  time.Time              `json:"created_at"`
	Dimensions ImageDimensions        `json:"dimensions"`
	FileName   string                 `json:"file_name"`
	Id         openapi_types.UUID     `json:"id"`
	MimeType   AvatarMetadataMimeType `json:"mime_type"`

	// Size Размер исходного файла в байтах.
	Size       int64       `json:"size"`
	Thumbnails []Thumbnail `json:"thumbnails"`
	UpdatedAt  time.Time   `json:"updated_at"`
	UserId     string      `json:"user_id"`
}

// AvatarMetadataMimeType defines model for AvatarMetadata.MimeType.
type AvatarMetadataMimeType string

// ComponentHealth defines model for ComponentHealth.
type ComponentHealth struct {
	// Error Описание ошибки, если компонент недоступен.
	Error  *string               `json:"error,omitempty"`
	Status ComponentHealthStatus `json:"status"`
}

// ComponentHealthStatus defines model for ComponentHealth.Status.
type ComponentHealthStatus string

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// ErrorWithDetails defines model for ErrorWithDetails.
type ErrorWithDetails struct {
	Details string `json:"details"`
	Error   string `json:"error"`
}

// FileTooLargeError defines model for FileTooLargeError.
type FileTooLargeError struct {
	Error   string `json:"error"`
	MaxSize int64  `json:"max_size"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Components struct {
		Broker   ComponentHealth `json:"broker"`
		Database ComponentHealth `json:"database"`
		S3       ComponentHealth `json:"s3"`
	} `json:"components"`
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// ImageDimensions defines model for ImageDimensions.
type ImageDimensions struct {
	Height int `json:"height"`
	Width  int `json:"width"`
}

// Thumbnail defines model for Thumbnail.
type Thumbnail struct {
	Size ThumbnailSize `json:"size"`
	Url  string        `json:"url"`
}

// ThumbnailSize defines model for Thumbnail.Size.
type ThumbnailSize string

// AvatarId defines model for AvatarId.
type AvatarId = openapi_types.UUID

// UserIdHeader defines model for UserIdHeader.
type UserIdHeader = string

// AvatarNotFound defines model for AvatarNotFound.
type AvatarNotFound = Error

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// ListAvatarsParams defines parameters for ListAvatars.
type ListAvatarsParams struct {
	// XUserID Идентификатор пользователя, выполняющего операцию.
	XUserID UserIdHeader `json:"X-User-ID"`
}

// UploadAvatarMultipartBody defines parameters for UploadAvatar.
type UploadAvatarMultipartBody struct {
	// File Изображение JPEG, PNG или WebP. Максимальный размер — 10 МБ.
	File openapi_types.File `json:"file"`
}

// UploadAvatarParams defines parameters for UploadAvatar.
type UploadAvatarParams struct {
	// XUserID Идентификатор пользователя, выполняющего операцию.
	XUserID UserIdHeader `json:"X-User-ID"`
}

// DeleteAvatarParams defines parameters for DeleteAvatar.
type DeleteAvatarParams struct {
	// XUserID Идентификатор пользователя, выполняющего операцию.
	XUserID UserIdHeader `json:"X-User-ID"`
}

// GetAvatarParams defines parameters for GetAvatar.
type GetAvatarParams struct {
	// Size Запрашиваемый размер изображения. По умолчанию возвращается оригинал.
	Size *GetAvatarParamsSize `form:"size,omitempty" json:"size,omitempty"`
}

// GetAvatarParamsSize defines parameters for GetAvatar.
type GetAvatarParamsSize string

// UploadAvatarMultipartRequestBody defines body for UploadAvatar for multipart/form-data ContentType.
type UploadAvatarMultipartRequestBody UploadAvatarMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Получить список аватарок пользователя
	// (GET /api/v1/avatars)
	ListAvatars(w http.ResponseWriter, r *http.Request, params ListAvatarsParams)
	// Загрузить аватарку
	// (POST /api/v1/avatars)
	UploadAvatar(w http.ResponseWriter, r *http.Request, params UploadAvatarParams)
	// Удалить аватарку
	// (DELETE /api/v1/avatars/{avatar_id})
	DeleteAvatar(w http.ResponseWriter, r *http.Request, avatarId AvatarId, params DeleteAvatarParams)
	// Получить изображение аватарки
	// (GET /api/v1/avatars/{avatar_id})
	GetAvatar(w http.ResponseWriter, r *http.Request, avatarId AvatarId, params GetAvatarParams)
	// Получить метаданные аватарки
	// (GET /api/v1/avatars/{avatar_id}/metadata)
	GetAvatarMetadata(w http.ResponseWriter, r *http.Request, avatarId AvatarId)
	// Проверить состояние сервиса
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Получить список аватарок пользователя
// (GET /api/v1/avatars)
func (_ Unimplemented) ListAvatars(w http.ResponseWriter, r *http.Request, params ListAvatarsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Загрузить аватарку
// (POST /api/v1/avatars)
func (_ Unimplemented) UploadAvatar(w http.ResponseWriter, r *http.Request, params UploadAvatarParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Удалить аватарку
// (DELETE /api/v1/avatars/{avatar_id})
func (_ Unimplemented) DeleteAvatar(w http.ResponseWriter, r *http.Request, avatarId AvatarId, params DeleteAvatarParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить изображение аватарки
// (GET /api/v1/avatars/{avatar_id})
func (_ Unimplemented) GetAvatar(w http.ResponseWriter, r *http.Request, avatarId AvatarId, params GetAvatarParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить метаданные аватарки
// (GET /api/v1/avatars/{avatar_id}/metadata)
func (_ Unimplemented) GetAvatarMetadata(w http.ResponseWriter, r *http.Request, avatarId AvatarId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Проверить состояние сервиса
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAvatars operation middleware
func (siw *ServerInterfaceWrapper) ListAvatars(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAvatarsParams

	headers := r.Header

	// ------------- Required header parameter "X-User-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-ID")]; found {
		var XUserID UserIdHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-ID", valueList[0], &XUserID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-ID", Err: err})
			return
		}

		params.XUserID = XUserID

	} else {
		err := fmt.Errorf("Header parameter X-User-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAvatars(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadAvatar operation middleware
func (siw *ServerInterfaceWrapper) UploadAvatar(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params UploadAvatarParams

	headers := r.Header

	// ------------- Required header parameter "X-User-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-ID")]; found {
		var XUserID UserIdHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-ID", valueList[0], &XUserID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-ID", Err: err})
			return
		}

		params.XUserID = XUserID

	} else {
		err := fmt.Errorf("Header parameter X-User-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadAvatar(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAvatar operation middleware
func (siw *ServerInterfaceWrapper) DeleteAvatar(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "avatar_id" -------------
	var avatarId AvatarId

	err = runtime.BindStyledParameterWithOptions("simple", "avatar_id", chi.URLParam(r, "avatar_id"), &avatarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "avatar_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteAvatarParams

	headers := r.Header

	// ------------- Required header parameter "X-User-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-ID")]; found {
		var XUserID UserIdHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-ID", valueList[0], &XUserID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-ID", Err: err})
			return
		}

		params.XUserID = XUserID

	} else {
		err := fmt.Errorf("Header parameter X-User-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAvatar(w, r, avatarId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAvatar operation middleware
func (siw *ServerInterfaceWrapper) GetAvatar(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "avatar_id" -------------
	var avatarId AvatarId

	err = runtime.BindStyledParameterWithOptions("simple", "avatar_id", chi.URLParam(r, "avatar_id"), &avatarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "avatar_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAvatarParams

	// ------------- Optional query parameter "size" -------------

	err = runtime.BindQueryParameter("form", true, false, "size", r.URL.Query(), &params.Size)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "size", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAvatar(w, r, avatarId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAvatarMetadata operation middleware
func (siw *ServerInterfaceWrapper) GetAvatarMetadata(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "avatar_id" -------------
	var avatarId AvatarId

	err = runtime.BindStyledParameterWithOptions("simple", "avatar_id", chi.URLParam(r, "avatar_id"), &avatarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "avatar_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAvatarMetadata(w, r, avatarId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/avatars", wrapper.ListAvatars)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/avatars", wrapper.UploadAvatar)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/avatars/{avatar_id}", wrapper.DeleteAvatar)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/avatars/{avatar_id}", wrapper.GetAvatar)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/avatars/{avatar_id}/metadata", wrapper.GetAvatarMetadata)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xabW8bx7X+K4u59+OSXEq0LBO4H3LjxNGFb+rWDlLUEowVORLXJXeZ3aVjVyCgl7i2",
	"q8Cq0wAJ0LRpm/Y7TYvWmpKov3DmL/SXFOfM7PtSIhUVKWAYFLkzc+a8POc55+wWazidrmNz2/dYfYt1",
	"TdfscJ+79Nd7j0zfdFea+LnJvYZrdX3LsVmdwbdwCCM4FbsQiC8ggDEMxC5MxLYGAxjSHwOxDWMIykxn",
	"Fq7pmn6L6cw2O5zVmUl7P7CaTGcu/6xnubzJ6r7b4zrzGi3eMfHUDcftmD6rs16PnvSfdHGx57uWvcn6",
	"fZ194nF3pfkRN5vcnU/OM5jAsfgSjmCiJB7BsTjQNRiKffkrnIoD8VK8gBG8gYkGEziDkdiGgfgtBOIl",
	"Xo0/NjvdNgrV87hbqi4shvdtSZmiG/+yhLKWVm6ee+OOZd/m9qbfYvVq/r59XOp1HdvjCQt97PgfOj2b",
	"7NRwbJ/bPn40u9221TBRFZWHHupjKxZ3i3HXdVzU0e9TBhtocAoj/G8A76T2YMD6SRn/2+UbrM7+qxI7",
	"T0X+6lU+oF1J0owpZjxmxfa5a5vtu9x9xF253eXu9RWcij2xK7ZpczTlgQYT8RwCeE0SiB2y5lDa9Cru",
	"OPeR0ZkJc1Iguk6Xu74lzdxwuenz5gPTTwVF0/R5ybc6PB8ZOrOaMwSQzjzf9HteQeT8DUYwFnvk/COU",
	"eyJ2KHQO4BQCNN1A7EAAp+Kp2IYJXhcm8A6D5DXeDV7DROyGCMDtXofV7+O9Gtzz8HB0ZbP5hOlsw7Ta",
	"vMnWCsTrue30NVyr6BYYew/kjfMQEQfbfUZKCJ+W20c60JN6joVx1h/yho+nSPP8P/fNpumbV2OmptXh",
	"tmc5tneR1610zE1+M368r7MNq80fSHjZurQHdKwOfyC/3YrsZOFhlYddjnaSf3Tt+PPnfL1baC/P+g0v",
	"cKa/wACO4AS9XoNA7IinMIFD8hgEVvEFocAxosJQg9f4FyHFU/Sd6AaW7S/VmM465mOrg3JWjdrytetL",
	"Bl7Cll8ZkVCW7fNN7qJUfqvXWbdNq01KtnzeuVDb98IltF7uaLqu+YTcrduc29CXddHYxklTKU2n/Cd1",
	"z5QzpyQu8uz3QwV8xM025p6sa/MQhzOG/TOcoT1hEIJCDHaBrsFI7MAxBBqMYQInlFRPZT4m+IdDiSpi",
	"DxMrnJbPR6jQOVskJCJHzw4/r+kXqFVtU3T7KMlMufP5G8vHpu77qeW3bnI/dD6z3f7ZBqvfnynD6FmR",
	"mvFG5wsVPpgXa62vsw+tNr/nOLdNd5NHl/9xknXMxw/C4I+ScRyfuRjOBmlG/mi74gtIN/2FokIFSJxm",
	"tanf1l3n15IrnnfPbEQgVJu+uW7K4+Zc6i3OvShr0PBw2kwPb1HkdlcbMHpSmUXHZfNSTuEtbm22fEVu",
	"FXAXofTnVlNCz3mPZYSUa/TwjCL5YiTPSRY5rNJT1TAeVw2D6WzRMB4vGsblOUlWmRKtcWleRnzYsjec",
	"PL6+d2dFg0MsSzQ4ggG8EdtiD44UusoKZk88I7YZUO1yhmRM7MAJsi/kYRql3V0YwCGh9KnYF081CDSx",
	"R98ch4vTldsExlNKJBjBu/KqvWrDN5FEbxXf3ccUENDzkgS+jXePeeFA7Ip92vCl2BU7dHSeS2p4L2LS",
	"RxotncCYCARyUdrthdycxIG/KmIdiB35xBFeT7zCVHOCe0NAB78U22JfI0kUI8HUpCnTo2KU7fH6AYyR",
	"satLa/CVJCdHeM2EOldtSoKRusQeqlze7EQcwBvKf6OMymGka1gSKPKDUqnfqepU6wO8Pt72d0TId2PS",
	"9JQugRsdQyBewGDVLtJjedVG97R8qlLJo7KGvuV0W3dcB6kG09kj7nrS/aplo2ygyztdbptdi9XZYtko",
	"I/5gNU8xVDG7VuVRtSILevpqk1O0Y6RRlbbSZHV22/L899QzeqrRMCXjxI9UUkV+fy1TBC8YxgwVYlza",
	"zcT/VCmWI38FRd8fpEnRVWePInGAe1+TohcJEl2xUlQRU+HY63RM9wmK8H2EBIHYFV9q5IwBhcF4Dol0",
	"5pubaBEWWgqTbdfx/ALq973YVmF1AgP098LIh5H2f3c+uKVrdz6+pUlX1T7l63fyEYhkUKsaGnwHr6TP",
	"ph3ok27bMZvKLlfgQZ/1uOf/r9N8knGeTq/tW13T9SuI8KWw1ON2w2kitCP0W7LVoFbdUzkqqpl0LSqZ",
	"wo9UMfVTLYZ0Lgr3zDWwZlZpGVU3IMSSNkETIya/Sylb++f215Gek+XVumWjO1F9FfWgIgZ3fn4j6Ysz",
	"W7rX1c8Fb3W+9k6yyGYLxkKtZFRLRvWeYdTp36+YrHzZtWsGX64ZRokv3Fgv1arNWsm8Xl0q1WpLS9eu",
	"1WqGQZk+ZEvp1gTleNby/a5Xr1QaTbusRCg3nE6IdZUZj4hKv7hHOHOvKcShWRpqZzIixQF+GfGGWds0",
	"KFNtJihNWCMqSCQGHcIhxfNbCFA4GMEJcQLxBUzENjolpv66JoOEwoMCQ4+7dn+SZSGciT1qOAW0xbvU",
	"FomGwZxdu2Q1VqRTPH2MBxHxoHRLpxP7UtwqjDmqYM+m3jojcjEtIqVXFy/Z4fy71IImq2zxXJbZyFEI",
	"38VzNLUMaFWchfE8s9bypWKR2lL9naMsLSzo8pyRfodiXzxXyUMh0lVmxW8SjFnmxfRwQuwVZry+niU1",
	"la1oXNGXXt/mfhFaf5WcHMiceB7/U25FmTqgkMyOT0ZRQyzLOTVaIXZJlbjoWJ64auOKSUSeD/HaR5L+",
	"i2dij1ruxahQJGC+WTeN3werdpZoz8Vei3L+TVL01eX8VOKpFRjwIkxF3WWVJIFz8dLA+R1M4K2seGL+",
	"TyxuV/G0Mf62Q3pESBwmq63MuC0JpV/H3bUYwEbihXgFp1eMm9P0Rn6HmnqLEajBIYXjG4QpdMViIvpS",
	"arR2MQhk5l9XiB0/KBvPgRt6WPjkhkJYjA5pbvgiosqpuBpN485hqqEHUWMYUHF5G4NBJvLKuVC6xf1p",
	"cZSR9xvlKQNq5aYS2naqj1+EA2UNiQB68gnZ9pkMcvFSg2FeD7LEnZCvvFH+chxNjD/rceKjaoCqeiix",
	"1zb5htlrIw90XGvTss12YtKU7+Xo8WMFza+Lq8rETCRVT+YJdJ4rxyOUSy4lmjTn2nyYvpI6FtshekQ+",
	"dE7jJo8wcrRNanrfbLR46X3H9l2nXVQlUjYMiMgRMIxhhH5FaWeonOMgIqt0OCVsWRYOKc2dyRIRYUTs",
	"0RDymfL71Dx1AsOUf8Sz+Y75uGRu8v9ZXqqRI+S1/ME9c3O+9wfoTMqigUa4uiP26IuYep+pW46k5jSq",
	"zhCPVW2mZqpBqJXBFPFX2dLy0vKN60s3lszrjeXrS+vX+SorsvhPD5zZVsQ0YMt7VWHvYa6MH72wQkOC",
	"c0hcpZMY4ha2qyK4jMa9l+o6zVm4pqfBYeO8aiwbUXu8emPBSI9+1bs05YfdzTlr38ToNz3xDYuFBXwy",
	"PT+9H7bNEwg7W7VsNStqCYna16OdYoSeeSe1RO60lh7JTtPuj6/DI2coAtfvsn32Ijf/DwzQk1nk/jeE",
	"ZyuaNRfzpu9j9AyLqeS8WKEn3kCSzWPi0dEo5I7j+Zsuv/vz27p2d7FEpGlIl1VthamVCOWcxMRBvreT",
	"nTkUMSw1vPvRUJEaX8YDy6hXFQ7xMlPJot/l6DH/S2JQmHp8pmjIzF+LoiE5j0F9DjFVy54J6lFy30D1",
	"h6g6Gco6mEZXMi0mGlQ0K5JhsPhTKzMqsL4lOUcwRt/TiNoiVaZh11sIVEQRv5F9ojFWN/G8Ltl+jCez",
	"KdMkvr5C4/yDpoPEt/ZVcaHeyEsbBwbh5DFjHIy67Ascp+ELbQmsSRCgaDKRfZEs4nD0IkkCae4+8Xze",
	"YWt0A48QrbBg+SMFaqrfnaCFIRuTxUum55nMOPVKpe00zHbL8fz6srFsUGJRwuQO/SFuvEwjNQOsyuL6",
	"JQROTHy5YLlQKWoTpZP+Wv9fAQAA///dSBbovCsAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
