// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AvatarStatus.
const (
	Failed     AvatarStatus = "failed"
	Processing AvatarStatus = "processing"
	Ready      AvatarStatus = "ready"
)

// Defines values for AvatarMetadataMimeType.
const (
	Imagejpeg AvatarMetadataMimeType = "image/jpeg"
	Imagepng  AvatarMetadataMimeType = "image/png"
	Imagewebp AvatarMetadataMimeType = "image/webp"
)

// Defines values for ComponentHealthStatus.
const (
	ComponentHealthStatusHealthy   ComponentHealthStatus = "healthy"
	ComponentHealthStatusUnhealthy ComponentHealthStatus = "unhealthy"
)

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusHealthy   HealthResponseStatus = "healthy"
	HealthResponseStatusUnhealthy HealthResponseStatus = "unhealthy"
)

// Defines values for LiveResponseStatus.
const (
	Live LiveResponseStatus = "live"
)

// Defines values for ThumbnailSize.
const (
	ThumbnailSizeN100x100 ThumbnailSize = "100x100"
	ThumbnailSizeN300x300 ThumbnailSize = "300x300"
)

// Defines values for GetAvatarParamsSize.
const (
	GetAvatarParamsSizeN100x100 GetAvatarParamsSize = "100x100"
	GetAvatarParamsSizeN300x300 GetAvatarParamsSize = "300x300"
	GetAvatarParamsSizeOriginal GetAvatarParamsSize = "original"
)

// Avatar defines model for Avatar.
type Avatar struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`

	// Status Текущее состояние асинхронной обработки.
	Status AvatarStatus `json:"status"`
	Url    string       `json:"url"`
	UserId string       `json:"user_id"`
}

// AvatarStatus Текущее состояние асинхронной обработки.
type AvatarStatus string

// AvatarMetadata defines model for AvatarMetadata.
type AvatarMetadata struct {
	CreatedAt  time.Time              `json:"created_at"`
	Dimensions ImageDimensions        `json:"dimensions"`
	FileName   string                 `json:"file_name"`
	Id         openapi_types.UUID     `json:"id"`
	MimeType   AvatarMetadataMimeType `json:"mime_type"`

	// Size Размер исходного файла в байтах.
	Size       int64       `json:"size"`
	Thumbnails []Thumbnail `json:"thumbnails"`
	UpdatedAt  time.Time   `json:"updated_at"`
	UserId     string      `json:"user_id"`
}

// AvatarMetadataMimeType defines model for AvatarMetadata.MimeType.
type AvatarMetadataMimeType string

// ComponentHealth defines model for ComponentHealth.
type ComponentHealth struct {
	// Error Описание ошибки, если компонент недоступен.
	Error  *string               `json:"error,omitempty"`
	Status ComponentHealthStatus `json:"status"`
}

// ComponentHealthStatus defines model for ComponentHealth.Status.
type ComponentHealthStatus string

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// ErrorWithDetails defines model for ErrorWithDetails.
type ErrorWithDetails struct {
	Details string `json:"details"`
	Error   string `json:"error"`
}

// FileTooLargeError defines model for FileTooLargeError.
type FileTooLargeError struct {
	Error   string `json:"error"`
	MaxSize int64  `json:"max_size"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Components struct {
		Broker   ComponentHealth `json:"broker"`
		Database ComponentHealth `json:"database"`
		S3       ComponentHealth `json:"s3"`
	} `json:"components"`
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// ImageDimensions defines model for ImageDimensions.
type ImageDimensions struct {
	Height int `json:"height"`
	Width  int `json:"width"`
}

// LiveResponse defines model for LiveResponse.
type LiveResponse struct {
	Status LiveResponseStatus `json:"status"`
}

// LiveResponseStatus defines model for LiveResponse.Status.
type LiveResponseStatus string

// Thumbnail defines model for Thumbnail.
type Thumbnail struct {
	Size ThumbnailSize `json:"size"`
	Url  string        `json:"url"`
}

// ThumbnailSize defines model for Thumbnail.Size.
type ThumbnailSize string

// AvatarId defines model for AvatarId.
type AvatarId = openapi_types.UUID

// UserIdHeader defines model for UserIdHeader.
type UserIdHeader = string

// AvatarNotFound defines model for AvatarNotFound.
type AvatarNotFound = Error

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// ListAvatarsParams defines parameters for ListAvatars.
type ListAvatarsParams struct {
	// XUserID Идентификатор пользователя, выполняющего операцию.
	XUserID UserIdHeader `json:"X-User-ID"`
}

// UploadAvatarMultipartBody defines parameters for UploadAvatar.
type UploadAvatarMultipartBody struct {
	// File Изображение JPEG, PNG или WebP. Максимальный размер — 10 МБ.
	File openapi_types.File `json:"file"`
}

// UploadAvatarParams defines parameters for UploadAvatar.
type UploadAvatarParams struct {
	// XUserID Идентификатор пользователя, выполняющего операцию.
	XUserID UserIdHeader `json:"X-User-ID"`
}

// DeleteAvatarParams defines parameters for DeleteAvatar.
type DeleteAvatarParams struct {
	// XUserID Идентификатор пользователя, выполняющего операцию.
	XUserID UserIdHeader `json:"X-User-ID"`
}

// GetAvatarParams defines parameters for GetAvatar.
type GetAvatarParams struct {
	// Size Запрашиваемый размер изображения. По умолчанию возвращается оригинал.
	Size *GetAvatarParamsSize `form:"size,omitempty" json:"size,omitempty"`
}

// GetAvatarParamsSize defines parameters for GetAvatar.
type GetAvatarParamsSize string

// UploadAvatarMultipartRequestBody defines body for UploadAvatar for multipart/form-data ContentType.
type UploadAvatarMultipartRequestBody UploadAvatarMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Получить список аватарок пользователя
	// (GET /api/v1/avatars)
	ListAvatars(w http.ResponseWriter, r *http.Request, params ListAvatarsParams)
	// Загрузить аватарку
	// (POST /api/v1/avatars)
	UploadAvatar(w http.ResponseWriter, r *http.Request, params UploadAvatarParams)
	// Удалить аватарку
	// (DELETE /api/v1/avatars/{avatar_id})
	DeleteAvatar(w http.ResponseWriter, r *http.Request, avatarId AvatarId, params DeleteAvatarParams)
	// Получить изображение аватарки
	// (GET /api/v1/avatars/{avatar_id})
	GetAvatar(w http.ResponseWriter, r *http.Request, avatarId AvatarId, params GetAvatarParams)
	// Получить метаданные аватарки
	// (GET /api/v1/avatars/{avatar_id}/metadata)
	GetAvatarMetadata(w http.ResponseWriter, r *http.Request, avatarId AvatarId)
	// Проверить состояние сервиса
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Проверить жизнеспособность процесса
	// (GET /live)
	GetLive(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Получить список аватарок пользователя
// (GET /api/v1/avatars)
func (_ Unimplemented) ListAvatars(w http.ResponseWriter, r *http.Request, params ListAvatarsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Загрузить аватарку
// (POST /api/v1/avatars)
func (_ Unimplemented) UploadAvatar(w http.ResponseWriter, r *http.Request, params UploadAvatarParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Удалить аватарку
// (DELETE /api/v1/avatars/{avatar_id})
func (_ Unimplemented) DeleteAvatar(w http.ResponseWriter, r *http.Request, avatarId AvatarId, params DeleteAvatarParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить изображение аватарки
// (GET /api/v1/avatars/{avatar_id})
func (_ Unimplemented) GetAvatar(w http.ResponseWriter, r *http.Request, avatarId AvatarId, params GetAvatarParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить метаданные аватарки
// (GET /api/v1/avatars/{avatar_id}/metadata)
func (_ Unimplemented) GetAvatarMetadata(w http.ResponseWriter, r *http.Request, avatarId AvatarId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Проверить состояние сервиса
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Проверить жизнеспособность процесса
// (GET /live)
func (_ Unimplemented) GetLive(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAvatars operation middleware
func (siw *ServerInterfaceWrapper) ListAvatars(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAvatarsParams

	headers := r.Header

	// ------------- Required header parameter "X-User-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-ID")]; found {
		var XUserID UserIdHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-ID", valueList[0], &XUserID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-ID", Err: err})
			return
		}

		params.XUserID = XUserID

	} else {
		err := fmt.Errorf("Header parameter X-User-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAvatars(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadAvatar operation middleware
func (siw *ServerInterfaceWrapper) UploadAvatar(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params UploadAvatarParams

	headers := r.Header

	// ------------- Required header parameter "X-User-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-ID")]; found {
		var XUserID UserIdHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-ID", valueList[0], &XUserID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-ID", Err: err})
			return
		}

		params.XUserID = XUserID

	} else {
		err := fmt.Errorf("Header parameter X-User-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadAvatar(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAvatar operation middleware
func (siw *ServerInterfaceWrapper) DeleteAvatar(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "avatar_id" -------------
	var avatarId AvatarId

	err = runtime.BindStyledParameterWithOptions("simple", "avatar_id", chi.URLParam(r, "avatar_id"), &avatarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "avatar_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteAvatarParams

	headers := r.Header

	// ------------- Required header parameter "X-User-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-ID")]; found {
		var XUserID UserIdHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-ID", valueList[0], &XUserID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-ID", Err: err})
			return
		}

		params.XUserID = XUserID

	} else {
		err := fmt.Errorf("Header parameter X-User-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAvatar(w, r, avatarId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAvatar operation middleware
func (siw *ServerInterfaceWrapper) GetAvatar(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "avatar_id" -------------
	var avatarId AvatarId

	err = runtime.BindStyledParameterWithOptions("simple", "avatar_id", chi.URLParam(r, "avatar_id"), &avatarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "avatar_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAvatarParams

	// ------------- Optional query parameter "size" -------------

	err = runtime.BindQueryParameter("form", true, false, "size", r.URL.Query(), &params.Size)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "size", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAvatar(w, r, avatarId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAvatarMetadata operation middleware
func (siw *ServerInterfaceWrapper) GetAvatarMetadata(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "avatar_id" -------------
	var avatarId AvatarId

	err = runtime.BindStyledParameterWithOptions("simple", "avatar_id", chi.URLParam(r, "avatar_id"), &avatarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "avatar_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAvatarMetadata(w, r, avatarId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLive operation middleware
func (siw *ServerInterfaceWrapper) GetLive(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLive(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/avatars", wrapper.ListAvatars)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/avatars", wrapper.UploadAvatar)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/avatars/{avatar_id}", wrapper.DeleteAvatar)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/avatars/{avatar_id}", wrapper.GetAvatar)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/avatars/{avatar_id}/metadata", wrapper.GetAvatarMetadata)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/live", wrapper.GetLive)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xabW8bxxH+K4dtPx7Jo0XLMoF+SOPEUeGmaq0gRS3DOJEr8Vzyjrk7OnYFAnqJY7sK",
	"rDoNkABN67Zpv9O0aJ31Qv2F2b/QX1LM7N77USJlFSlgGBR5uzs7L888M3MbrOF0uo7Nbd9j9Q3WNV2z",
	"w33u0l/vPTB9011s4ucm9xqu1fUtx2Z1Bt/BPozgRGxDIL6AAA5hILZhLDY1GMCQ/hiITTiEoMx0ZuGa",
	"rum3mM5ss8NZnZm09z2ryXTm8s96lsubrO67Pa4zr9HiHRNPXXPcjumzOuv16En/URcXe75r2eus39fZ",
	"Jx53F5sfcbPJ3dnkPIUxHImv4ADGSuIRHIk9XYOh2JW/wonYE8/FMxjBaxhrMIZTGIlNGIgvIRDP8Wr8",
	"odnptlGonsfdUvXKXHjflpQpuvFvSyhrafHGmTfuWPYtbq/7LVav5u/bx6Ve17E9nrDQx47/odOzyU4N",
	"x/a57eNHs9ttWw0TVVG576E+NmJxNxh3XcdFHf0pZbCBBicwwv8G8FZqDwasn5Txpy5fY3X2k0rsPBX5",
	"q1f5gHYlSTOmmPKYRdvnrm22b3P3AXfldhe719dwInbEttikzdGUexqMxVMI4BVJILbImkNp08u448xH",
	"RmcmzEmB6Dpd7vqWNHPD5abPm/dMPxUUTdPnJd/q8Hxk6MxqThFAOvN80+95BZHzTxjBodgh5x+h3GOx",
	"RaGzBycQoOkGYgsCOBGPxSaM8bowhrcYJK/wbvAKxmI7RABu9zqsfgfv1eCeh4ejK5vNR0xna6bV5k12",
	"t0C8nttOX8O1im6BsXdP3jgPEXGw3WGkhPBpuX2kAz2p51gYZ/U+b/h4ijTPL7lvNk3fvBwzNa0Otz3L",
	"sb3zvG6xY67zG/HjfZ2tWW1+T8LLxoU9oGN1+D357UZkJwsPq9zvcrST/KNrx58/56vdQnt51h94gTP9",
	"HQZwAMfo9RoEYks8hjHsk8cgsIovCAWOEBWGGrzCvwgpHqPvRDewbH++xnTWMR9aHZSzatQWrl6bN/AS",
	"tvzKiISybJ+vcxel8lu9zqptWm1SsuXzzrnaXg6X0Hq5o+m65iNyt25zZkNf1EVjGydNpTSd8p/UPVPO",
	"nJK4yLPfDxXwETfbmHuyrs1DHM4Y9m9wivaEQQgKMdgFugYjsQVHEGhwCGM4pqR6IvMxwT/sS1QRO5hY",
	"4aR8NkKFztkiIRE5enb4+a5+jlrVNkW3j5LMhDufvbF8bOK+n1p+6wb3Q+cz2+1frbH6nakyjJ4VqRlv",
	"dLZQ4YN5se72dfah1ebLjnPLdNd5dPl3k6xjPrwXBn+UjOP4zMVwNkgz8kfbFV9AuulvFBUqQOI0q039",
	"tuo6v5dc8ax7ZiMCodr0zVVTHjfjUm9u5kVZg4aH02Z6eIsit7vcgNGTyiw6LpuXcgpvcWu95Styq4C7",
	"CKU/t5oSes56LCOkXKOHZxTJd8t6wCd7Sl5ZbesBfyc4iVNH/rQwQtRZVcN4WDUMprM5w3g4ZxgXJ0FZ",
	"+WR6wKV5GfFhy15z8oD+3tKiBvtYB2lwAAN4LTbFDhwoOJcl0454QvQ2oGLpFNmf2IJjpHtI/DTK89sw",
	"gH1KCydiVzzWINDEDn1zFC5Ol4pjOJxQk8EI3pZX7BUbvo0keqMI9i7mnICel6zzTbx7TEQHYlvs0obP",
	"xbbYoqPz5FXDexF1P9Bo6RgOibEg+aXdnsnNSRz4h2LygdiSTxzg9cQLzG3HuDcEdPBzsSl2NZJEUSDM",
	"hZoyPSpG2R6vH8Ahlgjq0hp8LdnQAV4zoc4Vm7JupC6xgyqXNzsWe/CaEu4oo3IY6RrWIIptoVTqdypz",
	"1foAr4+3/SNVANsxS3tMl8CNjiAQz2CwYhfpsbxio3taPpXF5FFZQ990uq0l10Fuw3T2gLuedL9q2Sgb",
	"6PJOl9tm12J1Nlc2ygh4XdNvUQxVzK5VeVCtyA4CfbXOCV4w0qgsXGyyOrtlef576hk91dmYkOLiRyqp",
	"rkL/bqbqvmIYU5SkcS05FeFUtV+ObRZUmX+WJkVXnT6KxB7ufVWKXiRIdMVKUQlOlWqv0zHdRyjCywgJ",
	"ArEtvtLIGQMKg8MZJNKZb66jRVhoKczuXcfzC7jmS7GpwuoYBujvhZEPI+0XSx/c1LWlj29q0lW1T/nq",
	"Uj4CkX1qVUOD7+GF9Nm0A33SbTtmU9nlEjzosx73/J87zUcZ5+n02r7VNV2/gghfCmtLbjecJkI7Qr8l",
	"extq1bJKilGRpmtRjRZ+pBKtn+pppHNRuGeuYza1SsuougEhlrQJmhgx+W1K2dp/Nr+J9Jys51YtG92J",
	"Crqo6RVRxrPzG0lfnNnSzbV+Lnirs/WTklU9u2JcqZWMasmoLhtGnf79jslSm129avCFmmGU+JXrq6Va",
	"tVkrmdeq86VabX7+6tVazTAo04eMI90LoRzPWr7f9eqVSqNpl5UI5YbTCbGuMuURUa0ZNyWnbm6FODRN",
	"B+9URqTYwy8j3jBtXwhlqk0FpQlrRBWQxKB92Kd4fgMBCgcjOCZOIL6AsdhEp8TUX9dkkFB4UGDocZvw",
	"r7IOhVOxQx2ugLZ4m9oi0aGYsU2YLP+KdIqnH+JBRDwo3dLpxL4Utwpjjkrm04m3zohcTItI6dW5C7ZU",
	"/yW1oMmyXjyVdT1yFMJ38RRNLQNaVYNhPE+ttXxtWqS2VEPpIEsLC9pKp6TfodgVT1XyUIh0mVnx2wRj",
	"lnkxPQ0RO4UZr69nSU1lI5qP9KXXt7lfhNZfJ0cVMieexf+UW1GmDigks/OaUdSBy3JOjVaIbVIlLjqS",
	"J67YuGIcked9vPaBpP/iidihHn8xKhQJmO8OTuL3wYqdJdozsdeinH+DFH15OT+VeGoFBjwPU1F3WSVJ",
	"4Jy7MHB+D2N4IyuemP8Ti9tWPO0Qf9siPSIkDpPVVma+l4TSb+J2XgxgI/FMvICTS8bNSXojv0NNvcEI",
	"1GCfwvE1whS6YjERfS41WjsfBDIDt0vEjh+UjWfADT0sfHJTKCxGhzSofBZR5VRcjSZx5zDV0IOoMQyo",
	"uLyNwSATeeVcKN3k/qQ4ysj7rfKUAfWOUwltMzU4KMKBsoZEAD35mGz7RAa5eK7BMK8HWeKOyVdeK385",
	"ikbUn/U48VE1sVU9lNhrm3zN7LWRBzqutW7ZZjsx2sr3cvT4sYJ+0vlVZWIIk6on8wQ6z5Xjmc0FlxJN",
	"mnFtPkxfSB2LzRA9Ih86o3GTRxg5Syc1vW82Wrz0vmP7rtMuqhIpGwZE5AgYDmGEfkVpZ6icYy8iq3Q4",
	"JWxZFg4pzZ3KEhFhROzQ1POJ8vvUAHcMw5R/xC8DdMyHJXOd/2xhvkaOkNfyB8vm+mwvLNCZlEUDjXB1",
	"S+zQFzH1PlW3HEnNaVSdIR6r2kwNcYNQK4MJ4q+w+YX5hevX5q/Pm9caC9fmV6/xFVZk8R8fOLOtiEnA",
	"lveqwt7DTBk/ekOGphJnkLhKJzE1LmxXRXAZzZcv1HWasXBNj5/DTn3VWDCifnz1+hUjPWtWL++U73fX",
	"Z6x9E7Pm9Ig5LBau4JPpge2dsG2eQNjpqmWrWVFLSNS+Hu0UI/TUO6klcqe76RnwJO2+ex0eOUMRuH6f",
	"7bMXufn/YYAeTyP3/yA8W9Fwu5g3vYzRMyymkgNqhZ54A0k2j4hHR6OQJcfz111++9e3dO32XIlI05Au",
	"q9oKEysRyjmJiYN8USg7cyhiWGpa+M5QkZqXxhPSqFcVTg0zY9Ci3+WsM/9LYjKZenyqaMgMfIuiITmP",
	"QX0OMVXLngnqUXLfQPWHqDoZyjqYRlcyLSYaVDQrkmEw92MrMyqwviM5R3CIvqcRtUWqTMOuNxCoiCJ+",
	"I/tEh1jdxPO6ZPsxHgWnTJP4+hKN82+aDhLf2lXFhXoFMG0cGISTx4xxMOqyb4ychG/QJbAmQYCiyUT2",
	"zbWIw9GbKwmkuf3I83lHdWRoDjwRK4pqLLFDYxAkVqqJN5bFs9hWw1MkpB8tLy+VVGvvSwKHLTk+GcuK",
	"G20lWxhbCJthk0+qINEVFLuFiHALxX5XPIi8gZQwtSOkRu1FbvAyfetEtKGSzjcmKeMAHSGlsQwyRydM",
	"MC6eQumqsBr9i7RTcpiR4Pwh1ZaVaaahnaQT9Uql7TTMdsvx/PqCsWAQa1DC5A79Ie6qTWKsAyy54+I0",
	"zIrIanJIeK7Hq02UTvp3+/8NAAD//43iUpwKLgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
