image:
  repository: gophprofile
  tag: latest
  pullPolicy: IfNotPresent

config:
  s3Endpoint: minio:9000
  publicBaseUrl: http://gophprofile.local
  otelEndpoint: jaeger:4317

secret:
  create: true
  existingSecret: ""
  values:
    databaseDsn: postgres://gophprofile:gophprofile@postgres:5432/gophprofile?sslmode=disable
    amqpUrl: amqp://gophprofile:gophprofile@rabbitmq:5672/
    s3AccessKey: gophprofile
    s3SecretKey: gophprofile-secret

server:
  replicaCount: 1
  autoscaling:
    enabled: false

worker:
  replicaCount: 1
  autoscaling:
    enabled: false

ingress:
  enabled: true
  host: gophprofile.local

monitoring:
  serviceMonitor:
    enabled: false

networkPolicy:
  enabled: false
