{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gophprofile.secretName" . }}
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_DSN: {{ required "secret.values.databaseDsn is required" .Values.secret.values.databaseDsn | quote }}
  AMQP_URL: {{ required "secret.values.amqpUrl is required" .Values.secret.values.amqpUrl | quote }}
  S3_ACCESS_KEY: {{ required "secret.values.s3AccessKey is required" .Values.secret.values.s3AccessKey | quote }}
  S3_SECRET_KEY: {{ required "secret.values.s3SecretKey is required" .Values.secret.values.s3SecretKey | quote }}
{{- end }}
